services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "4000:3000"
    volumes:
      - ./src:/usr/src/app/src
      - ./local:/usr/src/app/local
      - /usr/src/app/node_modules
      - hardware-store--db:/usr/db
    networks:
      - hardware-store--network

  bash:
    image: node:22
    volumes:
      - hardware-store--db:/usr/db
    command: bash
    networks:
      - hardware-store--network

networks:
  hardware-store--network:
    external: true

volumes:
  hardware-store--db:
    external: true